name: Test all versions
on:
  push:
    branches:
      - test-all-versions

jobs:
  plugin_test:
    name: asdf plugin test
    if: always()
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v2
        with:
          command: op --version
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: 1password-cli
      - name: Move 1password-cli plugin to plugins dir
        run: |
          mkdir -p ${HOME}/.asdf/plugins/
          mv 1password-cli ${HOME}/.asdf/plugins/
      - name:
        run: |
          pip3 install semver
          python .github/workflows/test-all-versions.py
